name: Release with GoReleaser

on:
  push:
    tags:
      - 'v*'  # Se activa en tags como v1.0.0, v0.1.5, etc.

permissions:
  contents: write  # Requerido para subir assets al Release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
